routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PesanController;
use App\Http\Controllers\LoginAdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.tamu');
});

Route::get('/kamar', function () {
    return view('layouts.kamar');
});

Route::resource('pesan','PesanController');
Route::get('laporan','PesanController@cetakForm')->name('laporan');
Route::get('cetak/{nama_pemesan}/{email}','PesanController@cetakLaporan')->name('cetak');


Route::group([
    'prefix'=>config('admin.path'),
], function(){



    Route::get('login','LoginAdminController@formLogin')->name('admin.login');
    Route::post('login','LoginAdminController@login');

    Route::group(['middleware'=>'auth:admin'], function(){
        Route::post('logout','LoginAdminController@logout')->name('admin.logout');

        Route::view('/','dashboard')->name('dashboard');

        
        Route::resource('book','BookController');
        // Route::delete('book_mass_destroy', [\App\Http\Controllers\BookController::class, 'massDestroy'])->name('book.mass_destroy');


        Route::group(['middleware'=>['can:role,"admin"']], function(){
            Route::resource('admin','AdminController');
            Route::resource('kamar','KamarController');
            Route::resource('data','DataController');

            // Route::get('/admin/kamar/', 'KamarController@index')->name('kamar.index');
            // Route::post('/form', 'KamarController@store')->name('store.form');
            // Route::get('/form/create', 'KamarController@create')->name('create.form');
            // Route::get('/admin/kamar/create{kamar}', 'KamarController@edit')->name('kamar.edit');
            // Route::get('/admin/kamar{kamar}', 'KamarController@update')->name('kamar.update');
            // Route::get('/delete/{id}', 'KamarController@delete')->name('kamar.destroy');
        });
       
    });
});

app/Models/Book.php
<?php

namespace App\Models;

use Carbon\Carbon;
use App\Models\Data;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Book extends Model
{
    use HasFactory;
    protected $guarded = ['id', 'created_at', 'updated_at'];

    protected $dates = [
        'time_from',
        'time_to',
    ];

    // protected $dateFormat = 'Y-m-d H:i:s';

    public $fillable = [
        'nama_pemesan',
        'email',
        'phone',
        'nama_tamu',
        'data_id',
        'time_from',
        'time_to',
        'jum_kamar',
    ];

    public function data()
    {
        return $this->belongsTo(Data::class);
    }

     /**
     * Set attribute to date format
     * @param $input
     */
    // public function setTimeFromAttribute($input)
    // {
    //     if ($input != null && $input != '') {
    //         $this->attributes['time_from'] = Carbon::createFromFormat('Y-m-d H:i', $input)->format('Y-m-d H:i');
    //     } else {
    //         $this->attributes['time_from'] = null;
    //     }
    // }

    /**
     * Get attribute from date format
     * @param $input
     *
     * @return string
     */
    public function getTimeFromAttribute($value)
    {
        return Carbon::parse($value)->format('d-m-y');
    }

    public function getTimeToAttribute($value)
    {
        return Carbon::parse($value)->format('d-m-y');
    }
    // public function getTimeFromAttribute($input)
    // {
    //     $zeroDate = str_replace(['Y', 'm', 'd'], ['0000', '00', '00'],'Y-m-d H:i:s');

    //     if ($input != $zeroDate && $input != null) {
    //         return Carbon::createFromFormat('Y-m-d H:i:s', $input)->format('Y-m-d H:i:s');
    //     } else {
    //         return '';
    //     }
    // }

    /**
     * Set attribute to date format
     * @param $input
     */
    // public function setTimeToAttribute($input)
    // {
    //     if ($input != null && $input != '') {
    //         $this->attributes['time_to'] = Carbon::createFromFormat('Y-m-d H:i', $input)->format('Y-m-d H:i');
    //     } else {
    //         $this->attributes['time_to'] = null;
    //     }
    // }

    /**
     * Get attribute from date format
     * @param $input
     *
     * @return string
     */
    // public function getTimeToAttribute($input)
    // {
    //     $zeroDate = str_replace(['Y', 'm', 'd'], ['0000', '00', '00'],'Y-m-d H:i');

    //     if ($input != $zeroDate && $input != null) {
    //         return Carbon::createFromFormat('Y-m-d H:i:s', $input)->format('Y-m-d H:i:s');
    //     } else {
    //         return '';
    //     }
    // }

    public function getStatusAttribute($input) {
        return [
            0 => 'Created',
            1 => 'Completed',
            2 => 'Cancelled',
        ][$input];
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Data;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Symfony\Component\HttpFoundation\Response;
use Validator;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request['search'] ?? "";
        if($search !=""){
            $book = Book::where('nama_pemesan','LIKE', "%$search%")->orWhere('time_from','LIKE', "%$search%")->get();
        }else{
            $book = Book::all();
        }
        // $data = Data::get()->pluck('nama_kamar', 'id');
   
        return view('book.index', compact('book'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {

        $data = Data::get()->pluck('nama_kamar', 'id');

        $nama_pemesan = $request->get('nama_pemesan');
        $email = $request->get('email');
        $phone = $request->get('phone');
        $nama_tamu = $request->get('nama_tamu');
        // $data_id = Data::get()->pluck('nama_kamar', 'id');
        $data_id = $data;
        $time_from = $request->get('time_from');
        $time_to = $request->get('time_to');
        $jum_kamar = $request->get('jum_kamar');

        return view('book.create', compact('nama_pemesan', 'email', 'phone','nama_tamu','data_id', 'time_from', 'time_to','jum_kamar'));
    // return view('book.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Book $book,Request $request)
    {
        $data = Data::get()->pluck('nama_kamar', 'id');

        $validator = Validator::make($request->all(), [
            'nama_pemesan'=>'required|min:3',
            'email'=>'required|email|min:3',
            'phone'=>'required|min:10',
            'nama_tamu'=>'required|min:3',
            'data_id'=>'required|string',
            'time_from'=>'required|date_format:Y-m-d',
            'time_to'=>'required|date_format:Y-m-d',
            'jum_kamar'=>'required',
        ]);


        Book::create([
            'nama_pemesan'=>$request->nama_pemesan,
            'email'=>$request->email,
            'phone'=>$request->phone,
            'nama_tamu'=>$request->nama_tamu,
            'data_id'=>$request->data_id,
            'time_from'=>$request->time_from,
            'time_to'=>$request->time_to,
            'jum_kamar'=>$request->jum_kamar,

        ]);

        return redirect()->route('book.index')->with([
            'message' => 'successfully created !',
            'alert-type' => 'success'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        return view('book.edit',['book'=>$book]); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        $book->status = $request->input('status');

        $book->update();
        return redirect()->route('book.index')->with([
            'message' => 'successfully updated !',
            'alert-type' => 'info'
        ]);
    }

    /**     
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        
        $book->delete();

        return redirect()->route('book.index')->with([
            'message' => 'successfully deleted !',
            'alert-type' => 'danger'
        ]);
    }

    // public function massDestroy(Request $request)
    // {
        
    //     Book::whereIn('id', request('ids'))->delete();

    //     return response()->noContent();
    // }
}

resources/views/book/create.blade.php
@extends('layouts.admin',['title'=>'Tambah Booking'])

@section('content-header')
<h1 class="m-0"><i class="fas fa-book"></i>Booking</h1>
@endsection

@section('content')
<div class="row">
    <div class="col-6">
        <form action="{{route('book.store')}}" method="post" class="card card-primary" enctype="multipart/form-data">
            <div class="card-header">
                <i class="fas fa-plus-circle"></i>Tambah
            </div>
            @csrf
            <div class="card-body">
                <div class="form-group">
                    <label for="nama_pemesan">Nama Pemesan</label>
                    <input type="text" name="nama_pemesan" class="form-control" />
                    @error('nama_pemesan')
                    <div class="invalid-feedback">{{$message}}</div>
                    @enderror
                </div>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" name="email" class="form-control" />
                    @error('email')
                    <div class="invalid-feedback">{{$message}}</div>
                    @enderror
                </div>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="phone">No Handphone</label>
                    <input type="number" name="phone" class="form-control" />
                    @error('phone')
                    <div class="invalid-feedback">{{$message}}</div>
                    @enderror
                </div>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="nama_tamu">Nama tamu</label>
                    <input type="text" name="nama_tamu" class="form-control" />
                    @error('nama_tamu')
                    <div class="invalid-feedback">{{$message}}</div>
                    @enderror
                </div>
            </div>
            <div class="card-body">
                <div class=<div class="form-group">
                    <label for="data">Tipe kamar</label>
                    <select class="form-control" name="data_id" id="data_id">
                        @foreach($data_id as $id => $data_id)
                        <option value="{{ $id }}">{{ $data_id }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="time_from">{{ __('Time From') }}</label>
                    <input type="date" class="form-control datetimepicker" id="time_from" name="time_from"
                        value="{{ old('time_from', $time_from) }}" />
                </div>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="time_to">{{ __('Time to') }}</label>
                    <input type="date" class="form-control datetimepicker" id="time_to" name="time_to"
                        value="{{ old('time_to', $time_to) }}" />
                </div>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="jum_kamar">jumlah kamar</label>
                    <input type="text" name="jum_kamar" class="form-control" />
                    @error('jum_kamar')
                    <div class="invalid-feedback">{{$message}}</div>
                    @enderror
                </div>
            </div>

            <div class="card-footer">
                <button class="btn btn-primary" type="submit">
                    Simpan
                </button>
            </div>
        </form>

    </div>
</div>
@endsection

@push('script-alt')
<script src="https://cdn.datatables.net/select/1.2.0/js/dataTables.select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js">
</script>
<script>
    $('.datetimepicker').datetimepicker({
            format: 'YYYY-MM-DD HH:mm',
            locale: 'en',
            sideBySide: true,
            icons: {
            up: 'fas fa-chevron-up',
            down: 'fas fa-chevron-down',
            previous: 'fas fa-chevron-left',
            next: 'fas fa-chevron-right'
            },
            stepping: 10
        });
</script>
@endpush

resources/views/book/edit.blade.php
@extends('layouts.admin',['title'=>'Edit Booking'])

@section('content-header')
<h1 class="m-0"><i class="fas fa-book"></i>Booking</h1>
@endsection

@section('content')
<div class="row">
    <div class="col-6">
        <form action="{{route('book.update',['book'=>$book->id])}}" method="post" class="card card-primary"
            enctype="multipart/form-data">
            @csrf

            @method('PUT')
            <div class="card-header">
                <i class="fas fa-plus-circle"></i>Silahkan Pilih Proses Sesuai Yang Ada
            </div>

            <div class="form-group">
                <label for="status">{{ __('Status') }}</label>
                <select class="form-control" name="status" id="status" value="{{$book->status}}">
                    <option value="0" {{ $book->status == 0 ? 'selected' : null }} >Created</option>
                    <option value="1" {{ $book->status == 1 ? 'selected' : null }} >Completed</option>
                    <option value="2" {{ $book->status == 2 ? 'selected' : null }} >Concelled</option>
                </select>
            </div>
            <div class="card-footer">
                <button class="btn btn-primary" type="submit">
                    Edit
                </button>
            </div>
        </form>

    </div>
</div>
@endsection

@push('script-alt')
<script src="https://cdn.datatables.net/select/1.2.0/js/dataTables.select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js">
</script>
<script>
    $('.datetimepicker').datetimepicker({
            format: 'YYYY-MM-DD HH:mm',
            locale: 'en',
            sideBySide: true,
            icons: {
            up: 'fas fa-chevron-up',
            down: 'fas fa-chevron-down',
            previous: 'fas fa-chevron-left',
            next: 'fas fa-chevron-right'
            },
            stepping: 10
        });
</script>
@endpush

resources/views/book/index.blade.php
@extends('layouts.admin',['title'=>'Booking'])

@section('content-header')
<h1 class="m-0"><i class="fas fa-book"></i>Booking</h1>
@endsection

@section('content')
<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <div class="row mb-2">
                <div class="col-8">
                    <a href="{{route('book.create')}}" class="btn btn-primary">
                        <i class="fas fa-plus-circle"></i>Tambah
                    </a>
                </div>
                <form action="" class="form-inline">
                    <div class=" input-group ml-auto col-15">
                        <input type="search" name="search" class="form-control"
                            placeholder="Cari Nama Atau Tgl Check In">

                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="submit">Go !</button>
                        </div>
                    </div>
                </form>
            </div>

        </div>

        <div class="card-body">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>

                        <th>No</th>
                        <th>Nama Pemesan</th>
                        <th>Tipe Kamar</th>
                        <th>Check In</th>
                        <th>Check Out</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $no = 1;?>
                    @forelse($book as $booking)

                    <td>{{ $no++ }}</td>
                    <td>{{ $booking->nama_pemesan }}</td>
                    <td>{{ $booking->data->nama_kamar }}</td>
                    <td>{{ $booking->time_from }}</td>
                    <td>{{ $booking->time_to }}</td>
                    <td>{{ $booking->status }}</td>
                    <td>
                        <a href="{{ route('book.edit', $booking->id) }}" class="btn btn-info">
                            <i class="fa fa-edit"></i>
                        </a>
                        <form onclick="return confirm('are you sure ? ')" class="d-inline"
                            action="{{ route('book.destroy', $booking->id) }}" method="POST">
                            @csrf
                            @method('delete')
                            <button class="btn btn-danger">
                                <i class="fa fa-trash"></i>
                            </button>
                        </form>
                    </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="9" class="text-center">{{ __('Data Empty') }}</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>

        </div>
    </div>
</div>
<!-- Content Row -->

@endsection