routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PesanController;
use App\Http\Controllers\LoginAdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.tamu');
});

Route::get('/kamar', function () {
    return view('layouts.kamar');
});

Route::resource('pesan','PesanController');
Route::get('laporan','PesanController@cetakForm')->name('laporan');
Route::get('cetak/{nama_pemesan}/{email}','PesanController@cetakLaporan')->name('cetak');


Route::group([
    'prefix'=>config('admin.path'),
], function(){



    Route::get('login','LoginAdminController@formLogin')->name('admin.login');
    Route::post('login','LoginAdminController@login');

    Route::group(['middleware'=>'auth:admin'], function(){
        Route::post('logout','LoginAdminController@logout')->name('admin.logout');

        Route::view('/','dashboard')->name('dashboard');

        
        Route::resource('book','BookController');
        // Route::delete('book_mass_destroy', [\App\Http\Controllers\BookController::class, 'massDestroy'])->name('book.mass_destroy');


        Route::group(['middleware'=>['can:role,"admin"']], function(){
            Route::resource('admin','AdminController');
            Route::resource('kamar','KamarController');
            Route::resource('data','DataController');

            // Route::get('/admin/kamar/', 'KamarController@index')->name('kamar.index');
            // Route::post('/form', 'KamarController@store')->name('store.form');
            // Route::get('/form/create', 'KamarController@create')->name('create.form');
            // Route::get('/admin/kamar/create{kamar}', 'KamarController@edit')->name('kamar.edit');
            // Route::get('/admin/kamar{kamar}', 'KamarController@update')->name('kamar.update');
            // Route::get('/delete/{id}', 'KamarController@delete')->name('kamar.destroy');
        });
       
    });
});

resources/views/layouts/inc_admin/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">

        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                {{Auth::user()->name}} <i class="fas fa-caret-down"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <i class="fas fa-user mr-2"></i>My Akun
                </a>
                <div class="dropdown-divider"></div>

                <a href="{{route('admin.logout')}}"
                    onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
                    class="dropdown-item">
                    <i class="fas fa-sign-out-alt mr-2"></i>Log out
                </a>
                <form action="{{route('admin.logout')}}" id="logout-form" method="post">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

resources/views/layouts/inc_admin/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{route('dashboard')}}" class="brand-link">
        <img src="/adminlte/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
            style="opacity: .8">
        <span class="brand-text font-weight-light">Hotel Hebat </span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <x-nav-item label="Booking" icon="fas fa-book" :link="route('book.index')"></x-nav-item>
                @can('role','admin')
                <x-nav-item label="Kamar" icon="fas fa-bed" :link="route('data.index')"></x-nav-item>
                <x-nav-item label="User Admin" icon="fas fa-users" :link="route('admin.index')"></x-nav-item>
                @endcan
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>