routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PesanController;
use App\Http\Controllers\LoginAdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.tamu');
});

Route::get('/kamar', function () {
    return view('layouts.kamar');
});

Route::resource('pesan','PesanController');
Route::get('laporan','PesanController@cetakForm')->name('laporan');
Route::get('cetak/{nama_pemesan}/{email}','PesanController@cetakLaporan')->name('cetak');


Route::group([
    'prefix'=>config('admin.path'),
], function(){



    Route::get('login','LoginAdminController@formLogin')->name('admin.login');
    Route::post('login','LoginAdminController@login');

    Route::group(['middleware'=>'auth:admin'], function(){
        Route::post('logout','LoginAdminController@logout')->name('admin.logout');

        Route::view('/','dashboard')->name('dashboard');

        
        Route::resource('book','BookController');
        // Route::delete('book_mass_destroy', [\App\Http\Controllers\BookController::class, 'massDestroy'])->name('book.mass_destroy');


        Route::group(['middleware'=>['can:role,"admin"']], function(){
            Route::resource('admin','AdminController');
            Route::resource('kamar','KamarController');
            Route::resource('data','DataController');

            // Route::get('/admin/kamar/', 'KamarController@index')->name('kamar.index');
            // Route::post('/form', 'KamarController@store')->name('store.form');
            // Route::get('/form/create', 'KamarController@create')->name('create.form');
            // Route::get('/admin/kamar/create{kamar}', 'KamarController@edit')->name('kamar.edit');
            // Route::get('/admin/kamar{kamar}', 'KamarController@update')->name('kamar.update');
            // Route::get('/delete/{id}', 'KamarController@delete')->name('kamar.destroy');
        });
       
    });
});

app/Models/Data.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Data extends Model
{
    use HasFactory;

    public $timestamps = false;

    public $fillable = [
        'nama_kamar',
        'foto_kamar',
        'jum_kamar',
        'fasilitas_kamar',
        'fasilitas_umum'
    ];
}

app/Http/Controllers/DataController.php
<?php

namespace App\Http\Controllers;

use App\Models\Data;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class DataController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Data::select('id','nama_kamar','jum_kamar','fasilitas_kamar','fasilitas_umum')
                ->paginate(100);
        return view('data.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('data.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'nama_kamar'=>'required|min:3',
            'jum_kamar'=>'required',
            'fasilitas_kamar'=>'required|min:3',
            'fasilitas_umum'=>'required|min:3',
        ]);


        Data::create([
            'nama_kamar'=>$request->nama_kamar,
            'jum_kamar'=>$request->jum_kamar,
            'fasilitas_kamar'=>$request->fasilitas_kamar,
            'fasilitas_umum'=>$request->fasilitas_umum,
        ]);

        return redirect()->route('data.index')->with('status','store');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Data $data)
    {
        return view('data.edit',['item'=>$data]); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $data = Data::find($id);
        
        
        $data->nama_kamar = $request->input('nama_kamar');
        $data->jum_kamar = $request->input('jum_kamar');
        $data->fasilitas_kamar = $request->input('fasilitas_kamar');
        $data->fasilitas_umum = $request->input('fasilitas_umum');
        
        $data->update();
        return redirect()->route('data.index')->with('status','update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Data::find($id);
        $data->delete();
        return redirect()->route('data.index')->with('status','update');
    }
}

resources/views/data/create.blade.php
@extends('layouts.admin',['title'=>'Tambah Kamar'])

@section('content-header')
<h1 class="m-0"><i class="fas fa-bed"></i>Kamar</h1>
@endsection

@section('content')
<div class="row">
    <div class="col-6">
        <form action="{{route('data.store')}}" method="post" class="card card-primary" enctype="multipart/form-data">
            <div class="card-header">
                <i class="fas fa-plus-circle"></i>Tambah
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label>Nama </label>
                    <input type="text" name="nama_kamar"
                        class="form-control{{ $errors->has('nama_kamar') ? ' is-invalid':'' }}" />
                    @error('nama_kamar')
                    <div class="invalid-feedback">{{$message}}</div>
                    @enderror
                </div>

            </div>
            <div class="card-body">
                <div class="form-group">
                    <label>Jumlah</label>
                    <input type="number" name="jum_kamar"
                        class="form-control{{ $errors->has('jum_kamar') ? ' is-invalid':'' }}" />
                    @error('jum_kamar')
                    <div class="invalid-feedback">{{$message}}</div>
                    @enderror
                </div>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label>fasilitas Kamar </label>
                    <input type="text" name="fasilitas_kamar"
                        class="form-control{{ $errors->has('fasilitas_kamar') ? ' is-invalid':'' }}" />
                    @error('fasilitas_kamar')
                    <div class="invalid-feedback">{{$message}}</div>
                    @enderror
                </div>

            </div>
            <div class="card-body">
                <div class="form-group">
                    <label>fasilitas umum</label>
                    <input type="text" name="fasilitas_umum"
                        class="form-control{{ $errors->has('fasilitas_umum') ? ' is-invalid':'' }}" />
                    @error('fasilitas_umum')
                    <div class="invalid-feedback">{{$message}}</div>
                    @enderror
                </div>

            </div>


            <div class="card-footer">
                <button class="btn btn-primary" type="submit">
                    Simpan
                </button>
            </div>
        </form>

    </div>
</div>
@endsection

resources/views/data/edit.blade.php
@extends('layouts.admin',['title'=>'Edit Kamar'])

@section('content-header')
<h1 class="m-0"><i class="fas fa-bed"></i>Kamar</h1>
@endsection

@section('content')
<div class="row">
    <div class="col-6">
        <form action="{{route('data.update',['data'=>$item->id])}}" method="post" class="card card-primary"
            enctype="multipart/form-data">
            @csrf

            @method('PUT')

            <div class="card-header">
                <i class="fas fa-plus-circle"></i>Edit
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label>Nama </label>
                    <input type="text" name="nama_kamar"
                        class="form-control{{ $errors->has('nama_kamar') ? ' is-invalid':'' }}"
                        value="{{$item->nama_kamar}}" />
                    @error('nama_kamar')
                    <div class=" invalid-feedback">{{$message}}
                    </div>
                    @enderror
                </div>

                <div class="card-body">
                    <div class="form-group">
                        <label>Jumlah</label>
                        <input type="number" name="jum_kamar"
                            class="form-control{{ $errors->has('jum_kamar') ? ' is-invalid':'' }}"
                            value="{{$item->jum_kamar}}" />
                        @error('jum_kamar')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label>fasilitas Kamar </label>
                        <input type="text" name="fasilitas_kamar"
                            class="form-control{{ $errors->has('fasilitas_kamar') ? ' is-invalid':'' }}"
                            value="{{$item->fasilitas_kamar}}" />
                        @error('fasilitas_kamar')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>

                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label>fasilitas umum</label>
                        <input type="text" name="fasilitas_umum"
                            class="form-control{{ $errors->has('fasilitas_umum') ? ' is-invalid':'' }}"
                            value="{{$item->fasilitas_umum}}" />
                        @error('fasilitas_umum')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>

                </div>


                <div class="card-footer">
                    <button class="btn btn-primary" type="submit">
                        Update
                    </button>
                </div>
        </form>

    </div>
</div>
@endsection

resources/views/data/index.blade.php
@extends('layouts.admin',['title'=>'Kamar'])

@section('content-header')
<h1 class="m-0"><i class="fas fa-bed"></i>Kamar</h1>
@endsection

@section('content')

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col">
                <a href="{{route('data.create')}}" class="btn btn-primary">
                    <i class="fas fa-plus-circle"></i>Tambah
                </a>
            </div>
        </div>
    </div>
    <div class="card-body p-0">
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Nama Kamar</th>
                    <th>Jumlah Kamar</th>
                    <th>fasilitas Kamar</th>
                    <th>fasilitas Umum</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                <?php $no = 1;?>
                @foreach ($data as $item)
                <tr>
                    <td>{{$no++}}</td>
                    <td>{{$item->nama_kamar}}</td>
                    <td>{{$item->jum_kamar}}</td>
                    <td>{{$item->fasilitas_kamar}}</td>
                    <td>{{$item->fasilitas_umum}}</td>
                    <td>


                        <a href="{{route('data.edit',['data'=>$item->id])}}" class="btn btn-primary">
                            <i class="fas fa-edit"></i>
                        </a>


                    </td>
                    <td>
                        <form onclick="return confirm('are you sure ? ')"
                            action="{{route('data.destroy',['data'=>$item->id])}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger"> <i class="fas fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="card-body pb-0">

    </div>
</div>

@endsection

@section('modal')
<!-- Modal -->
<div class="kamar fade" id="kamarDelete" data-backdrop="static" data-keyboard="false" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Understood</button>
            </div>
        </div>
    </div>
</div>
@endsection