routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PesanController;
use App\Http\Controllers\LoginAdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.tamu');
});

Route::get('/kamar', function () {
    return view('layouts.kamar');
});

Route::resource('pesan','PesanController');
Route::get('laporan','PesanController@cetakForm')->name('laporan');
Route::get('cetak/{nama_pemesan}/{email}','PesanController@cetakLaporan')->name('cetak');


Route::group([
    'prefix'=>config('admin.path'),
], function(){



    Route::get('login','LoginAdminController@formLogin')->name('admin.login');
    Route::post('login','LoginAdminController@login');

    Route::group(['middleware'=>'auth:admin'], function(){
        Route::post('logout','LoginAdminController@logout')->name('admin.logout');

        Route::view('/','dashboard')->name('dashboard');

        
        Route::resource('book','BookController');
        // Route::delete('book_mass_destroy', [\App\Http\Controllers\BookController::class, 'massDestroy'])->name('book.mass_destroy');


        Route::group(['middleware'=>['can:role,"admin"']], function(){
            Route::resource('admin','AdminController');
            Route::resource('kamar','KamarController');
            Route::resource('data','DataController');

            // Route::get('/admin/kamar/', 'KamarController@index')->name('kamar.index');
            // Route::post('/form', 'KamarController@store')->name('store.form');
            // Route::get('/form/create', 'KamarController@create')->name('create.form');
            // Route::get('/admin/kamar/create{kamar}', 'KamarController@edit')->name('kamar.edit');
            // Route::get('/admin/kamar{kamar}', 'KamarController@update')->name('kamar.update');
            // Route::get('/delete/{id}', 'KamarController@delete')->name('kamar.destroy');
        });
       
    });
});

app/Http/Controllers/PesanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Data;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Gate;
use Symfony\Component\HttpFoundation\Response;
use Validator;

class PesanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Data::all();
        $book = Book::all();
        return view('pesan.index', compact('book','data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $data = Data::get()->pluck('nama_kamar', 'id');
        
        $data = Data::get()->pluck('nama_kamar', 'id');
        $nama_pemesan = $request->get('nama_pemesan');
        $email = $request->get('email');
        $phone = $request->get('phone');
        $nama_tamu = $request->get('nama_tamu');
        $data_id = Data::get()->pluck('nama_kamar', 'id');
        $time_from = $request->get('time_from');
        $time_to = $request->get('time_to');
        $jum_kamar = $request->get('jum_kamar');
        
        
        return view('pesan.create', compact('nama_pemesan', 'email', 'phone','nama_tamu','data_id', 'time_from', 'time_to','jum_kamar'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Book $book,Request $request)
    {
        $data = Data::get()->pluck('nama_kamar', 'id');

        $validator = Validator::make($request->all(), [
            'nama_pemesan'=>'required|min:3',
            'email'=>'required|email|min:3',
            'phone'=>'required|min:10',
            'nama_tamu'=>'required|min:3',
            'data_id'=>'required|string',
            'time_from'=>'required|date_format:Y-m-d',
            'time_to'=>'required|date_format:Y-m-d',
            'jum_kamar'=>'required',
        ]);


        Book::create([
            'nama_pemesan'=>$request->nama_pemesan,
            'email'=>$request->email,
            'phone'=>$request->phone,
            'nama_tamu'=>$request->nama_tamu,
            'data_id'=>$request->data_id,
            'time_from'=>$request->time_from,
            'time_to'=>$request->time_to,
            'jum_kamar'=>$request->jum_kamar,

        ]);
        return redirect()->route('laporan');
    }

    public function cetakForm()
    {
        return view('pesan.laporan');
    }

    public function cetakLaporan($nama_pemesan ,$email)
    {
        $cetak = Book::with('data')->whereBetween('nama_pemesan',[$nama_pemesan, $email])->get();

        return view('pesan.cetak', compact('cetak'));
        // dd($cetak);
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pesan/cetak.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hotel Hebat</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="/adminlte/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/adminlte/dist/css/adminlte.min.css">

    <link rel="stylesheet" href="/css/style.css">
</head>

<body class="hold-transition">
    <!-- As a link -->

    <!-- <div class="container content">
        @yield('content')
    </div> -->
    <div class="container content">
        <h1 class="text-center my-4">Silahkan di Screen Shot atau Print untuk bukti</h1>
        <form action="" method="post" class="card card-primary col-12" enctype="multipart/form-data">

            <div class="card-body">
                <table class="table table-hover table-striped">
                    <thead>
                        <tr>

                            <th>No</th>
                            <th>Nama Pemesan</th>
                            <th>Tipe Kamar</th>
                            <th>Check In</th>
                            <th>Check Out</th>
                            <th>Jumlah Kamar</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $no = 1;?>
                        @forelse($cetak as $booking)

                        <td>{{ $no++ }}</td>
                        <td>{{ $booking->nama_pemesan }}</td>
                        <td>{{ $booking->data->nama_kamar }}</td>
                        <td>{{ $booking->time_from }}</td>
                        <td>{{ $booking->time_to }}</td>
                        <td>{{ $booking->jum_kamar }}</td>

                        </tr>
                        @empty
                        <tr>
                            <td colspan="9" class="text-center">{{ __('Data Empty') }}</td>
                        </tr>
                        @endforelse
                    </tbody>

                </table>

                <div class=" col-1 ml-auto pt-4">
                    <a href="{{ route('pesan.index') }}" class="btn btn-secondary">
                        <i class="fa fa-back">Home</i>
                    </a>
                </div>
            </div>


        </form>
        @yield('modal')

        <!-- jQuery -->
        <script src="/adminlte/plugins/jquery/jquery.min.js"></script>
        <!-- Bootstrap 4 -->
        <script src="/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- AdminLTE App -->
        <script src="/adminlte/dist/js/adminlte.min.js"></script>
</body>

</html>

resources/views/pesan/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hotel Hebat</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="/adminlte/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/adminlte/dist/css/adminlte.min.css">

    <link rel="stylesheet" href="../../css/style.css">
</head>

<body class="hold-transition">
    <!-- As a link -->
    @include('layouts.inc_tamu.navbar')

    <!-- <div class="container content">
        @yield('content')
    </div> -->
    <div class="row">
        <div class="col-10">
            <h1 class="text-center my-4">Silahkan isi data untuk pesan</h1>
            <form action="{{route('pesan.store')}}" method="post"
                class="card card-primary my-5 ml-xl-5 my-lg-5 mx-5 pb-5 " enctype="multipart/form-data">

                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="nama_pemesan">Nama Pemesan</label>
                        <input type="text" name="nama_pemesan" class="form-control" />
                        @error('nama_pemesan')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="text" name="email" class="form-control" />
                        @error('email')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="phone">No Handphone</label>
                        <input type="number" name="phone" class="form-control" />
                        @error('phone')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="nama_tamu">Nama tamu</label>
                        <input type="text" name="nama_tamu" class="form-control" />
                        @error('nama_tamu')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                </div>
                <div class="card-body">
                    <div class=<div class="form-group">
                        <label for="data">Tipe kamar</label>
                        <select class="form-control" name="data_id" id="data_id">
                            @foreach($data_id as $id => $data_id)
                            <option value="{{ $id }}">{{ $data_id }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="time_from">Check In</label>
                        <input type="date" class="form-control datetimepicker" id="time_from" name="time_from"
                            value="{{ old('time_from', $time_from) }}" />
                    </div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="time_to">Check Out</label>
                        <input type="date" class="form-control datetimepicker" id="time_to" name="time_to"
                            value="{{ old('time_to', $time_to) }}" />
                    </div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="jum_kamar">jumlah kamar</label>
                        <input type="text" name="jum_kamar" class="form-control" />
                        @error('jum_kamar')
                        <div class="invalid-feedback">{{$message}}</div>
                        @enderror
                    </div>
                </div>

                <div class="card-footer">
                    <button class="btn btn-primary" type="submit">
                        Pesan
                    </button>
                </div>
            </form>

        </div>
    </div>
    @yield('modal')

    <footer class="footer">
        <div class="container">
            <span class="text-muted"><strong>Copyright &copy; Dhio Anugrah.</strong> </span>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="/adminlte/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/adminlte/dist/js/adminlte.min.js"></script>
</body>

</html>

resources/views/pesan/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hotel Hebat</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="/adminlte/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/adminlte/dist/css/adminlte.min.css">

    <link rel="stylesheet" href="/css/style.css">
</head>

<body class="hold-transition">
    <!-- As a link -->
    @include('layouts.inc_tamu.navbar')

    <div class="container-fluid p-0">
        <img src="images/bg.jpg" class="img img-fluid w-100">
    </div>
    <form method="get" action="{{route('pesan.create')}}"
        class=" bg-white py-2 px-1 form-pesan border shadow text-center">
        <div class="col-md-12 text-center">
            <button type="submit" class="btn btn-block btn-secondary">Pesan</button>
        </div>
    </form>

    <!-- <div class="container content">
        @yield('content')
    </div> -->
    <div class="container content">
        <h1 class="text-center my-4">Kamar</h1>

        <div class="row kamar ">
            <div class="col-md-4">
                <img src="images/kamar_suite.jpg" class="img-fluid rounded img-thumbnail" />
            </div>
            <div class="col-md-3">
                <h2>Deluxe Room</h2>
                <span>
                    Fasilitas :
                </span><br>
                <span>- Coffe maker</span><br>
                <span>- AC</span><br>
                <span>- LED TV 32 inch</span>
                <p>
                    Rp. 400. 000 / malam
                </p>
                <p>
                    <button type="button" class="btn btn-default pull-right"><a href="{{route('pesan.create')}}">Pesan
                            Sekarang</a></button>
                </p>
            </div>
        </div>

        <div class="row kamar ">
            <div class="col-md-4">
                <img src="images/kamar_standar.jpg" class="img-fluid rounded img-thumbnail" />
            </div>
            <div class="col-md">
                <h2>Ekonomi Room</h2>
                <span>
                    Fasilitas :
                </span><br>
                <span>- Coffe maker</span><br>
                <span>- AC</span><br>
                <span>- LED TV 32 inch</span>
                <p>
                    Rp. 400. 000 / malam
                </p>
                <p>
                    <button type="button" class="btn btn-default pull-right"><a href="{{route('pesan.create')}}">Pesan
                            Sekarang</a></button>
                </p>
            </div>
        </div>

    </div>

    @yield('modal')

    <footer class="footer">
        <div class="container">
            <span class="text-muted"><strong>Copyright &copy; Dhio Anugrah.</strong> </span>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="/adminlte/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/adminlte/dist/js/adminlte.min.js"></script>
</body>

</html>

resources/views/pesan/laporan.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hotel Hebat</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="/adminlte/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/adminlte/dist/css/adminlte.min.css">

    <link rel="stylesheet" href="/css/style.css">
</head>

<body class="hold-transition">
    <!-- As a link -->
    @include('layouts.inc_tamu.navbar')

    <!-- <div class="container content">
        @yield('content')
    </div> -->
    <div class="container content">
        <h1 class="text-center my-4">Cetak Bukti Reservasi</h1>
        <form action="{{route('book.store')}}" method="get" class="card card-primary col-7"
            enctype="multipart/form-data">

            <div class="card-body">
                <div class="form-group">
                    <label for="nama_pemesan">Nama Pemesan</label>
                    <input type="text" name="nama_pemesan" id="nama_pemesan" class="form-control" />
                </div>
            </div>

            <div class="card-body">
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" name="email" id="email" class="form-control" />
                </div>
            </div>

            <div class="card col-3 ml-auto">
                <a href="" onclick="this.href='/cetak/'+document.getElementById('nama_pemesan').value + 
                '/' + document.getElementById('email').value" class="btn btn-primary">Cetak Bukti</a>
            </div>
        </form>
        @yield('modal')

        <footer class="footer">
            <div class="container">
                <span class="text-muted"><strong>Copyright &copy; Dhio Anugrah.</strong> </span>
            </div>
        </footer>

        <!-- jQuery -->
        <script src="/adminlte/plugins/jquery/jquery.min.js"></script>
        <!-- Bootstrap 4 -->
        <script src="/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- AdminLTE App -->
        <script src="/adminlte/dist/js/adminlte.min.js"></script>
</body>

</html>